// https://leetcode.com/problems/remove-palindromic-subsequences/

/*
Given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string, if it is generated by deleting some characters of a given string without changing its order.

A string is called palindrome if is one that reads the same backward as well as forward.
*/

class Solution {
public:
	int removePalindromeSub(string& s) {
		if (s.size() == 0) return 0;
		if (ispal(s)) return 1;
		else return 2;
	}
	
	bool ispal(string& s) {
		int i=0, j=s.size()-1;
		while (i < j) {
			if (s[i] != s[j]) return false;
			i++, j--;
		}
		return true;
	}
};